### ISSUE TITLE
_pickle.PicklingError:

### ISSUE THREAD

**Issue by Kokoing123** [ORippler/gaussian-ad-mvtec#1]
when I was used, on the val step, program crashed by error:"_pickle.PicklingError: Can't pickle <function MVTecAD.<lambda> at 0x000002EC4FA7A8B8>: attribute lookup MVTecAD.<lambda> on src.datasets.mvtecad failed".

**Comment by ORippler** [comment]
Hi,

did you make sure to set up the environment by using `environment.yml` ? Also, which OS are you on? As stated in the Readme, Code is written in `Python 3.7` and was tested only on `Ubuntu 18.04` using the specified `environment.yml`. If you follow instructions, you shouldn't get this error.

Nonetheless, my guess the pickling error comes from the [lambda function](https://github.com/ORippler/gaussian-ad-mvtec/blob/main/src/datasets/mvtecad.py#L135) used to specify the default value for `target_transform`.

Best,

**Comment by Kokoing123** [comment]
thank you very much, I thought the reason is that platform os, my os is windows 10, and now I use ubuntu 18.04 to test it, it work well.

**Comment by ORippler** [comment]
Glad it's working for you now :)
