### ISSUE TITLE
Applying custom dataset without ground truth masks

### ISSUE THREAD

**Issue by andreluizbvs** [ORippler/gaussian-ad-mvtec#2]
Is it possible to test on my own dataset considering there are no ground truth masks?
I created my own `my_ad_dataset.py`, but without success. 

In other words, I would like to apply this method only in image-level anomaly detection. Is it possible to do it without major code changes?

**Comment by ORippler** [comment]
Hi,

I would assume that the code itself runs fine if you provide dummy values for the [`min_anomaly_size`](https://github.com/ORippler/gaussian-ad-mvtec/blob/main/src/datasets/mvtecad.py#L390-L408) of your dataset as well as generate random masks by sampling from [`np.random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)`(0,1, size=(image.shape[0], image.shape[1]))`. This would of course give you nonsensical values for everything the gt-masks are used for (it's not used for image-level AD calculation of the Gaussian AD method). Sampling from `np.random.randint` is necessary so ROC-computation does not error out when only identical values are present in the gt.

Refer [here](https://github.com/ORippler/gaussian-ad-mvtec/blob/main/src/datasets/mvtecad.py#L318-L321) on where zero-value masks are generated for `good` images, which also do not have ground-truth segmentation masks available.

Best,

**Comment by bartproo** [comment]
Hi, if masks are not required in the gaussian model, why do we need it in the test_step?
