### ISSUE TITLE
Question about mask

### ISSUE THREAD

**Issue by bartproo** [ORippler/gaussian-ad-mvtec#4]
Hi, if masks are not required in the gaussian model, why do we need it in the test_step? Can I set load_masks to false?

**Comment by ORippler** [comment]
Hi,

we also tested around with anomaly segmentation (provided e.g. by Autoencoder), and need the masks for evaluating these methods (results didn't make it into the paper and padim beat us to gaussian anomaly segmentation)

you can try setting it to `false`, but I don't know what will happen exactly, see #2 for a better workaround
